// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model/food_model/objectbox_model/food_model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 5263930361897727211),
      name: 'Food',
      lastPropertyId: const IdUid(31, 5366111589490474485),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 5301365717599655232),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7377346063538664229),
            name: 'userId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 6179608065616682971),
            relationTarget: 'User'),
        ModelProperty(
            id: const IdUid(3, 3330081752668938617),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5080397115424411192),
            name: 'foodTypes',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 4685671319494554155),
            name: 'duration',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 1642526519936246487),
            name: 'serving',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 4158206764988908672),
            name: 'difficulty',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(8, 3521214037965269206),
            name: 'tags',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(9, 3820146398678149029),
            name: 'water',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(10, 2504016805899006015),
            name: 'energy',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(11, 7190789844084708690),
            name: 'protein',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(12, 4332760521111508542),
            name: 'fat',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(13, 7535668432303297987),
            name: 'carbohydrate',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(14, 869466929543253006),
            name: 'fiber',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(15, 3741146930999361171),
            name: 'calcium',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(16, 683449714729504126),
            name: 'iron',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(17, 3725140886269777045),
            name: 'phosphor',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(18, 5532428137260382052),
            name: 'potassium',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(19, 2301573935661923239),
            name: 'sodium',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(20, 14498855817561280),
            name: 'zinc',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(21, 6164108965771071196),
            name: 'copper',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(22, 2610613380420148766),
            name: 'vitaminC',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(23, 8520671450635556048),
            name: 'vitaminB1',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(24, 6465474963942018882),
            name: 'vitaminB2',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(25, 8500847979050416180),
            name: 'vitaminB3',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(26, 3420103133910105705),
            name: 'retinol',
            type: 8,
            flags: 0),
        ModelProperty(
            id: const IdUid(27, 2214761450242455632),
            name: 'foodId',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(28, 5227375609840779980),
            name: 'session',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(29, 5677312023459543818),
            name: 'date',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(30, 5460371108322994448),
            name: 'instruction',
            type: 30,
            flags: 0),
        ModelProperty(
            id: const IdUid(31, 5366111589490474485),
            name: 'imageFileName',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 937332134421631514),
      name: 'User',
      lastPropertyId: const IdUid(1, 2916353400714214596),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2916353400714214596),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(name: 'foods', srcEntity: 'Food', srcField: '')
      ])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 937332134421631514),
      lastIndexId: const IdUid(1, 6179608065616682971),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Food: EntityDefinition<Food>(
        model: _entities[0],
        toOneRelations: (Food object) => [object.user],
        toManyRelations: (Food object) => {},
        getId: (Food object) => object.id,
        setId: (Food object, int id) {
          object.id = id;
        },
        objectToFB: (Food object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          final foodTypesOffset = object.foodTypes == null
              ? null
              : fbb.writeList(object.foodTypes!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final difficultyOffset = object.difficulty == null
              ? null
              : fbb.writeString(object.difficulty!);
          final tagsOffset =
              object.tags == null ? null : fbb.writeString(object.tags!);
          final sessionOffset = fbb.writeString(object.session);
          final dateOffset = fbb.writeString(object.date);
          final instructionOffset = object.instruction == null
              ? null
              : fbb.writeList(object.instruction!
                  .map(fbb.writeString)
                  .toList(growable: false));
          final imageFileNameOffset = object.imageFileName == null
              ? null
              : fbb.writeString(object.imageFileName!);
          fbb.startTable(32);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.user.targetId);
          fbb.addOffset(2, nameOffset);
          fbb.addOffset(3, foodTypesOffset);
          fbb.addInt64(4, object.duration);
          fbb.addInt64(5, object.serving);
          fbb.addOffset(6, difficultyOffset);
          fbb.addOffset(7, tagsOffset);
          fbb.addFloat64(8, object.water);
          fbb.addFloat64(9, object.energy);
          fbb.addFloat64(10, object.protein);
          fbb.addFloat64(11, object.fat);
          fbb.addFloat64(12, object.carbohydrate);
          fbb.addFloat64(13, object.fiber);
          fbb.addFloat64(14, object.calcium);
          fbb.addFloat64(15, object.iron);
          fbb.addFloat64(16, object.phosphor);
          fbb.addFloat64(17, object.potassium);
          fbb.addFloat64(18, object.sodium);
          fbb.addFloat64(19, object.zinc);
          fbb.addFloat64(20, object.copper);
          fbb.addFloat64(21, object.vitaminC);
          fbb.addFloat64(22, object.vitaminB1);
          fbb.addFloat64(23, object.vitaminB2);
          fbb.addFloat64(24, object.vitaminB3);
          fbb.addFloat64(25, object.retinol);
          fbb.addInt64(26, object.foodId);
          fbb.addOffset(27, sessionOffset);
          fbb.addOffset(28, dateOffset);
          fbb.addOffset(29, instructionOffset);
          fbb.addOffset(30, imageFileNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Food(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 8),
              foodTypes:
                  const fb.ListReader<String>(fb.StringReader(asciiOptimization: true), lazy: false)
                      .vTableGetNullable(buffer, rootOffset, 10),
              duration: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 12),
              serving: const fb.Int64Reader()
                  .vTableGetNullable(buffer, rootOffset, 14),
              date: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 60, ''),
              session: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 58, ''),
              difficulty: const fb.StringReader(asciiOptimization: true)
                  .vTableGetNullable(buffer, rootOffset, 16),
              tags: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 18),
              water: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 20),
              energy: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 22),
              protein: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 24),
              fat: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 26),
              carbohydrate: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 28),
              fiber: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 30),
              calcium: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 32),
              iron: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 34),
              phosphor: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 36),
              potassium: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 38),
              sodium: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 40),
              zinc: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 42),
              copper: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 44),
              vitaminC: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 46),
              vitaminB1: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 48),
              vitaminB2: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 50),
              vitaminB3: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 52),
              retinol: const fb.Float64Reader().vTableGetNullable(buffer, rootOffset, 54),
              foodId: const fb.Int64Reader().vTableGetNullable(buffer, rootOffset, 56),
              instruction: const fb.ListReader<String>(fb.StringReader(asciiOptimization: true), lazy: false).vTableGetNullable(buffer, rootOffset, 62),
              imageFileName: const fb.StringReader(asciiOptimization: true).vTableGetNullable(buffer, rootOffset, 64));
          object.user.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.user.attach(store);
          return object;
        }),
    User: EntityDefinition<User>(
        model: _entities[1],
        toOneRelations: (User object) => [],
        toManyRelations: (User object) => {
              RelInfo<Food>.toOneBacklink(
                      2, object.id, (Food srcObject) => srcObject.user):
                  object.foods
            },
        getId: (User object) => object.id,
        setId: (User object, int id) {
          object.id = id;
        },
        objectToFB: (User object, fb.Builder fbb) {
          fbb.startTable(2);
          fbb.addInt64(0, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = User(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));
          InternalToManyAccess.setRelInfo(
              object.foods,
              store,
              RelInfo<Food>.toOneBacklink(
                  2, object.id, (Food srcObject) => srcObject.user),
              store.box<User>());
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Food] entity fields to define ObjectBox queries.
class Food_ {
  /// see [Food.id]
  static final id = QueryIntegerProperty<Food>(_entities[0].properties[0]);

  /// see [Food.user]
  static final user =
      QueryRelationToOne<Food, User>(_entities[0].properties[1]);

  /// see [Food.name]
  static final name = QueryStringProperty<Food>(_entities[0].properties[2]);

  /// see [Food.foodTypes]
  static final foodTypes =
      QueryStringVectorProperty<Food>(_entities[0].properties[3]);

  /// see [Food.duration]
  static final duration =
      QueryIntegerProperty<Food>(_entities[0].properties[4]);

  /// see [Food.serving]
  static final serving = QueryIntegerProperty<Food>(_entities[0].properties[5]);

  /// see [Food.difficulty]
  static final difficulty =
      QueryStringProperty<Food>(_entities[0].properties[6]);

  /// see [Food.tags]
  static final tags = QueryStringProperty<Food>(_entities[0].properties[7]);

  /// see [Food.water]
  static final water = QueryDoubleProperty<Food>(_entities[0].properties[8]);

  /// see [Food.energy]
  static final energy = QueryDoubleProperty<Food>(_entities[0].properties[9]);

  /// see [Food.protein]
  static final protein = QueryDoubleProperty<Food>(_entities[0].properties[10]);

  /// see [Food.fat]
  static final fat = QueryDoubleProperty<Food>(_entities[0].properties[11]);

  /// see [Food.carbohydrate]
  static final carbohydrate =
      QueryDoubleProperty<Food>(_entities[0].properties[12]);

  /// see [Food.fiber]
  static final fiber = QueryDoubleProperty<Food>(_entities[0].properties[13]);

  /// see [Food.calcium]
  static final calcium = QueryDoubleProperty<Food>(_entities[0].properties[14]);

  /// see [Food.iron]
  static final iron = QueryDoubleProperty<Food>(_entities[0].properties[15]);

  /// see [Food.phosphor]
  static final phosphor =
      QueryDoubleProperty<Food>(_entities[0].properties[16]);

  /// see [Food.potassium]
  static final potassium =
      QueryDoubleProperty<Food>(_entities[0].properties[17]);

  /// see [Food.sodium]
  static final sodium = QueryDoubleProperty<Food>(_entities[0].properties[18]);

  /// see [Food.zinc]
  static final zinc = QueryDoubleProperty<Food>(_entities[0].properties[19]);

  /// see [Food.copper]
  static final copper = QueryDoubleProperty<Food>(_entities[0].properties[20]);

  /// see [Food.vitaminC]
  static final vitaminC =
      QueryDoubleProperty<Food>(_entities[0].properties[21]);

  /// see [Food.vitaminB1]
  static final vitaminB1 =
      QueryDoubleProperty<Food>(_entities[0].properties[22]);

  /// see [Food.vitaminB2]
  static final vitaminB2 =
      QueryDoubleProperty<Food>(_entities[0].properties[23]);

  /// see [Food.vitaminB3]
  static final vitaminB3 =
      QueryDoubleProperty<Food>(_entities[0].properties[24]);

  /// see [Food.retinol]
  static final retinol = QueryDoubleProperty<Food>(_entities[0].properties[25]);

  /// see [Food.foodId]
  static final foodId = QueryIntegerProperty<Food>(_entities[0].properties[26]);

  /// see [Food.session]
  static final session = QueryStringProperty<Food>(_entities[0].properties[27]);

  /// see [Food.date]
  static final date = QueryStringProperty<Food>(_entities[0].properties[28]);

  /// see [Food.instruction]
  static final instruction =
      QueryStringVectorProperty<Food>(_entities[0].properties[29]);

  /// see [Food.imageFileName]
  static final imageFileName =
      QueryStringProperty<Food>(_entities[0].properties[30]);
}

/// [User] entity fields to define ObjectBox queries.
class User_ {
  /// see [User.id]
  static final id = QueryIntegerProperty<User>(_entities[1].properties[0]);
}
